import '@/app/globals.css';
import React from 'react';

export const metadata = {
  title: 'Unified ERP - Real Estate & Treasury',
  description: 'Generated by Jules',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ar" dir="rtl">
      <body className="min-h-screen bg-background font-sans antialiased">
        <div className="flex">
          <nav className="w-64 p-4 border-l border-border h-screen bg-card text-card-foreground">
            <h2 className="text-lg font-semibold border-b pb-2 mb-4">نظام ERP الموحد</h2>
            <ul className="space-y-2">
              <li><a href="/dashboard" className="hover:underline">لوحة التحكم</a></li>
              <li className="pt-4 border-b pb-4">
                <span className="font-semibold text-sm text-muted-foreground">العقارات</span>
                <ul className="space-y-2 pr-4 mt-2">
                    <li><a href="/real-estate/installments" className="hover:underline">الأقساط</a></li>
                    <li><a href="/real-estate/partners" className="hover:underline">الشركاء</a></li>
                    <li><a href="/real-estate/returns" className="hover:underline">المرتجعات</a></li>
                </ul>
              </li>
              <li className="pt-4">
                <span className="font-semibold text-sm text-muted-foreground">المحاسبة</span>
                 <ul className="space-y-2 pr-4 mt-2">
                    <li><a href="/accounting/vouchers" className="hover:underline">السندات</a></li>
                    <li><a href="/accounting/transfers" className="hover:underline">التحويلات</a></li>
                    <li><a href="/accounting/bank-imports" className="hover:underline">كشف البنك</a></li>
                </ul>
              </li>
              <li className="pt-4">
                <span className="font-semibold text-sm text-muted-foreground">التقارير</span>
                 <ul className="space-y-2 pr-4 mt-2">
                    <li><a href="/reports" className="hover:underline">عرض التقارير</a></li>
                </ul>
              </li>
               <li className="pt-4 border-t mt-4">
                <span className="font-semibold text-sm text-muted-foreground">النظام</span>
                 <ul className="space-y-2 pr-4 mt-2">
                    <li><a href="/system/backups" className="hover:underline">النسخ الاحتياطي</a></li>
                </ul>
              </li>
            </ul>
          </nav>
          <main className="flex-1 p-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
